#!/bin/bash
if [ -z $1 ]; then
    BASE_DIR=$(realpath "$(dirname $0)")
else
    BASE_DIR=$(realpath "$1")
fi

cd ${BASE_DIR}/resources
docker-compose -f docker-compose.bwbots.yml -f docker-compose.roscore.yml stop
