[tool.black]
line-length = 120
skip-string-normalization = true
extend_exclude = '^/(env|frontend|docker|notebooks|ros/)'

[tool.isort]
multi_line_output = 3
line_length = 120
include_trailing_comma = true

[tool.pyright]
