#      1 ------- 2
#     /.        /|
#    0 ------- 3 |
#    | .       | |
#    | 5.......| 6
#    |.        |/
#    4 ------- 7

#          z+ x+
#          | /
#          |/
#  y+ ---- o

# points are relative to the center coordinate (meters)
# 0 = (-x, -y,  z)
# 1 = ( x,  y,  z)
# 2 = ( x, -y,  z)
# 3 = (-x, -y,  z)
# 4 = (-x, -y, -z)
# 5 = ( x,  y, -z)
# 7 = ( x, -y, -z)
# 8 = (-x, -y, -z)

bw_yolo/XYZKeypoint[8] points
geometry_msgs/Vector3 dimensions
