//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class BwSequenceElementMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/BwSequenceElement";
        public override string RosMessageName => k_RosMessageName;

        public ulong parameters;

        public BwSequenceElementMsg()
        {
            this.parameters = 0;
        }

        public BwSequenceElementMsg(ulong parameters)
        {
            this.parameters = parameters;
        }

        public static BwSequenceElementMsg Deserialize(MessageDeserializer deserializer) => new BwSequenceElementMsg(deserializer);

        private BwSequenceElementMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.parameters);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.parameters);
        }

        public override string ToString()
        {
            return "BwSequenceElementMsg: " +
            "\nparameters: " + parameters.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
