//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class WaypointArrayMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/WaypointArray";
        public override string RosMessageName => k_RosMessageName;

        public WaypointMsg[] waypoints;

        public WaypointArrayMsg()
        {
            this.waypoints = new WaypointMsg[0];
        }

        public WaypointArrayMsg(WaypointMsg[] waypoints)
        {
            this.waypoints = waypoints;
        }

        public static WaypointArrayMsg Deserialize(MessageDeserializer deserializer) => new WaypointArrayMsg(deserializer);

        private WaypointArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.waypoints, WaypointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.waypoints);
            serializer.Write(this.waypoints);
        }

        public override string ToString()
        {
            return "WaypointArrayMsg: " +
            "\nwaypoints: " + System.String.Join(", ", waypoints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
