//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class WaypointMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/Waypoint";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public string name;
        public Geometry.PoseMsg pose;

        public WaypointMsg()
        {
            this.header = new Std.HeaderMsg();
            this.name = "";
            this.pose = new Geometry.PoseMsg();
        }

        public WaypointMsg(Std.HeaderMsg header, string name, Geometry.PoseMsg pose)
        {
            this.header = header;
            this.name = name;
            this.pose = pose;
        }

        public static WaypointMsg Deserialize(MessageDeserializer deserializer) => new WaypointMsg(deserializer);

        private WaypointMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.name);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.name);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "WaypointMsg: " +
            "\nheader: " + header.ToString() +
            "\nname: " + name.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
