- startup
- charging
- driving
- hotspot
- hotspot_charging
- idle
- bot99
- fur_elise
- cs1_1pre
- cs6_1pre
- cs6_6gig
- brawl
- mii_channel
- megalovania
- ruins
- dedede
- pokemon_center
- scale3
- nokia
