#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

RM_PATTERN="$1"

if [ -z "${RM_PATTERN}" ]; then
    echo "Removal pattern is empty! Exiting."
    exit 1
fi

PROJECT_DIR=$(realpath "${BASE_DIR}/../../")

rm -r ${PROJECT_DIR}/src/bw_data/data/"${RM_PATTERN}"

IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
PROJECT_NAME=$(${BASE_DIR}/../get_project_name)

docker run \
    --user ${ORGANIZATION} \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=${PROJECT_NAME}_build:/home/${ORGANIZATION}/ros_ws:rw \
    -v ${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw \
    -v ${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw \
    --rm \
    --gpus all \
    ${IMAGE_VERSION} \
    bash /opt/${ORGANIZATION}/scripts/delete_data.sh "${RM_PATTERN}"
