version: "3"

services:
  bwbots:
    image: bwbots:latest
    container_name: bwbots
    restart: on-failure
    environment:
      - ROS_MAP_NAME=3-101
      - OBJECT_MODEL_NAMES=powercell_2021.names
    network_mode: "host"
    privileged: true
    volumes:
      - /home/${USER}/bwbots-beer-caddy/ros1/bwbots:/home/${USER}/ros_ws/src:rw
      - /home/${USER}/docker_ros_ws:/home/${USER}/bw_ros_ws:rw
      - /run/systemd:/run/systemd:rw
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority:rw
      # Allow container to control docker
      - /home/${USER}/.docker:/root/.docker:rw # docker looks here inside a container
      - /home/${USER}/.docker:/home/${USER}/.docker:rw # but we need to satisfy spice-lib.sh
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]