version: "3"

services:
  roscore:
    image: bwbots:latest
    container_name: roscore
    restart: "no"
    network_mode: "host"
    environment:
      - ROS_MASTER_INTERFACE=wlan0
    volumes:
      - /home/${USER}/bwbots-beer-caddy/ros1/scripts:/root/scripts:rw
    privileged: true
    entrypoint: ["/roscore.sh"]
    stop_signal: SIGTERM

