version: "3"

services:
  build_bwbots:
    image: bwbots:latest
    container_name: build_bwbots
    restart: "no"
    network_mode: "host"
    runtime: "nvidia"
    privileged: true
    group_add:
      - dialout
    volumes:
      - /home/${USER}/docker_ros_ws:/root/ros_ws:rw
      - /home/${USER}/bwbots-beer-caddy/ros1/bwbots:/root/ros_ws/src/bwbots:rw
      - /home/${USER}/bwbots-beer-caddy/ros1/scripts:/root/scripts:rw
      - /run/systemd:/run/systemd:rw
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority:rw
      # Allow container to control docker
      - /home/${USER}/.docker:/root/.docker:rw # docker looks here inside a container
      - /home/${USER}/.docker:/home/${USER}/.docker:rw
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/root/install/build_bwbots.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
