version: "3"

services:
  bwbots:
    image: bwbots:latest
    container_name: bwbots
    restart: "no"
    network_mode: "host"
    runtime: "nvidia"
    privileged: true
    stop_signal: SIGINT
    group_add:
      - dialout
    environment:
      - ROS_MASTER_INTERFACE=wlan0
    volumes:
      - /home/${USER}/docker_ros_ws:/root/ros_ws:rw
      - /home/${USER}/bwbots-beer-caddy/ros1/bwbots:/root/ros_ws/src/bwbots:rw
      - /home/${USER}/bwbots-beer-caddy/ros1/docker/resources/scripts:/root/scripts:rw
      - /home/${USER}/bwbots-beer-caddy/ros1/sequence_utils:/root/sequence_utils:rw
      - /home/${USER}/logs:/root/logs:rw
      - /home/${USER}/bags:/root/bags:rw
      - /run/systemd:/run/systemd:rw
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority:rw
    command: [ "/launch.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
