#!/usr/bin/env bash
export OPENBLAS_CORETYPE=ARMV8
source /home/${USER}/noetic_ws/install_isolated/setup.bash
. /usr/local/bin/ros_env 0 roscore
roscore & while ! echo exit | nc localhost 11311 > /dev/null; do sleep 1; done
