//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class CalibrateScaleRequest : Message
    {
        public const string k_RosMessageName = "bw_interfaces/CalibrateScale";
        public override string RosMessageName => k_RosMessageName;

        public float mass;

        public CalibrateScaleRequest()
        {
            this.mass = 0.0f;
        }

        public CalibrateScaleRequest(float mass)
        {
            this.mass = mass;
        }

        public static CalibrateScaleRequest Deserialize(MessageDeserializer deserializer) => new CalibrateScaleRequest(deserializer);

        private CalibrateScaleRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mass);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mass);
        }

        public override string ToString()
        {
            return "CalibrateScaleRequest: " +
            "\nmass: " + mass.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
