//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class GetAllWaypointsRequest : Message
    {
        public const string k_RosMessageName = "bw_interfaces/GetAllWaypoints";
        public override string RosMessageName => k_RosMessageName;


        public GetAllWaypointsRequest()
        {
        }
        public static GetAllWaypointsRequest Deserialize(MessageDeserializer deserializer) => new GetAllWaypointsRequest(deserializer);

        private GetAllWaypointsRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetAllWaypointsRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
