//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class GetAllWaypointsResponse : Message
    {
        public const string k_RosMessageName = "bw_interfaces/GetAllWaypoints";
        public override string RosMessageName => k_RosMessageName;

        public WaypointArrayMsg waypoints_array;

        public GetAllWaypointsResponse()
        {
            this.waypoints_array = new WaypointArrayMsg();
        }

        public GetAllWaypointsResponse(WaypointArrayMsg waypoints_array)
        {
            this.waypoints_array = waypoints_array;
        }

        public static GetAllWaypointsResponse Deserialize(MessageDeserializer deserializer) => new GetAllWaypointsResponse(deserializer);

        private GetAllWaypointsResponse(MessageDeserializer deserializer)
        {
            this.waypoints_array = WaypointArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.waypoints_array);
        }

        public override string ToString()
        {
            return "GetAllWaypointsResponse: " +
            "\nwaypoints_array: " + waypoints_array.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
