//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class GetWaypointsResponse : Message
    {
        public const string k_RosMessageName = "bw_interfaces/GetWaypoints";
        public override string RosMessageName => k_RosMessageName;

        public WaypointArrayMsg waypoints;
        public bool success;

        public GetWaypointsResponse()
        {
            this.waypoints = new WaypointArrayMsg();
            this.success = false;
        }

        public GetWaypointsResponse(WaypointArrayMsg waypoints, bool success)
        {
            this.waypoints = waypoints;
            this.success = success;
        }

        public static GetWaypointsResponse Deserialize(MessageDeserializer deserializer) => new GetWaypointsResponse(deserializer);

        private GetWaypointsResponse(MessageDeserializer deserializer)
        {
            this.waypoints = WaypointArrayMsg.Deserialize(deserializer);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.waypoints);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetWaypointsResponse: " +
            "\nwaypoints: " + waypoints.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
