//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class GetWaypointRequest : Message
    {
        public const string k_RosMessageName = "bw_interfaces/GetWaypoint";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public GetWaypointRequest()
        {
            this.name = "";
        }

        public GetWaypointRequest(string name)
        {
            this.name = name;
        }

        public static GetWaypointRequest Deserialize(MessageDeserializer deserializer) => new GetWaypointRequest(deserializer);

        private GetWaypointRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "GetWaypointRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
