//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class ListWifiResponse : Message
    {
        public const string k_RosMessageName = "bw_interfaces/ListWifi";
        public override string RosMessageName => k_RosMessageName;

        public WifiNetworkMsg[] networks;
        public bool success;
        public string message;

        public ListWifiResponse()
        {
            this.networks = new WifiNetworkMsg[0];
            this.success = false;
            this.message = "";
        }

        public ListWifiResponse(WifiNetworkMsg[] networks, bool success, string message)
        {
            this.networks = networks;
            this.success = success;
            this.message = message;
        }

        public static ListWifiResponse Deserialize(MessageDeserializer deserializer) => new ListWifiResponse(deserializer);

        private ListWifiResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.networks, WifiNetworkMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.networks);
            serializer.Write(this.networks);
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "ListWifiResponse: " +
            "\nnetworks: " + System.String.Join(", ", networks.ToList()) +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
