//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class ListWifiRequest : Message
    {
        public const string k_RosMessageName = "bw_interfaces/ListWifi";
        public override string RosMessageName => k_RosMessageName;

        public DurationMsg scan_time;

        public ListWifiRequest()
        {
            this.scan_time = new DurationMsg();
        }

        public ListWifiRequest(DurationMsg scan_time)
        {
            this.scan_time = scan_time;
        }

        public static ListWifiRequest Deserialize(MessageDeserializer deserializer) => new ListWifiRequest(deserializer);

        private ListWifiRequest(MessageDeserializer deserializer)
        {
            this.scan_time = DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.scan_time);
        }

        public override string ToString()
        {
            return "ListWifiRequest: " +
            "\nscan_time: " + scan_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
