//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class OdomResetRequest : Message
    {
        public const string k_RosMessageName = "bw_interfaces/OdomReset";
        public override string RosMessageName => k_RosMessageName;

        public double x;
        public double y;
        public double t;

        public OdomResetRequest()
        {
            this.x = 0.0;
            this.y = 0.0;
            this.t = 0.0;
        }

        public OdomResetRequest(double x, double y, double t)
        {
            this.x = x;
            this.y = y;
            this.t = t;
        }

        public static OdomResetRequest Deserialize(MessageDeserializer deserializer) => new OdomResetRequest(deserializer);

        private OdomResetRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.t);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.t);
        }

        public override string ToString()
        {
            return "OdomResetRequest: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nt: " + t.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
