//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class OdomResetResponse : Message
    {
        public const string k_RosMessageName = "bw_interfaces/OdomReset";
        public override string RosMessageName => k_RosMessageName;

        public bool resp;

        public OdomResetResponse()
        {
            this.resp = false;
        }

        public OdomResetResponse(bool resp)
        {
            this.resp = resp;
        }

        public static OdomResetResponse Deserialize(MessageDeserializer deserializer) => new OdomResetResponse(deserializer);

        private OdomResetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.resp);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.resp);
        }

        public override string ToString()
        {
            return "OdomResetResponse: " +
            "\nresp: " + resp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
