//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class SaveWaypointRequest : Message
    {
        public const string k_RosMessageName = "bw_interfaces/SaveWaypoint";
        public override string RosMessageName => k_RosMessageName;

        public WaypointMsg waypoint;

        public SaveWaypointRequest()
        {
            this.waypoint = new WaypointMsg();
        }

        public SaveWaypointRequest(WaypointMsg waypoint)
        {
            this.waypoint = waypoint;
        }

        public static SaveWaypointRequest Deserialize(MessageDeserializer deserializer) => new SaveWaypointRequest(deserializer);

        private SaveWaypointRequest(MessageDeserializer deserializer)
        {
            this.waypoint = WaypointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.waypoint);
        }

        public override string ToString()
        {
            return "SaveWaypointRequest: " +
            "\nwaypoint: " + waypoint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
