//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class StopSequenceResponse : Message
    {
        public const string k_RosMessageName = "bw_interfaces/StopSequence";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public StopSequenceResponse()
        {
            this.success = false;
        }

        public StopSequenceResponse(bool success)
        {
            this.success = success;
        }

        public static StopSequenceResponse Deserialize(MessageDeserializer deserializer) => new StopSequenceResponse(deserializer);

        private StopSequenceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "StopSequenceResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
