BOT99:
  tempo_multiplier: 2.0
  tracks: [0, 1, 2, 3, 4, 5, 6, 7]
  num_leds: 24
fur_elise:
  tracks: [0, 1, 2, 3, 4, 5, 6, 7]
brawl:
  tracks: [0, 1, 2, 3, 4, 5, 6, 7]
mii_channel:
  tracks: [0, 1, 2, 3, 4, 5, 6, 7]
  num_leds: 24
megalovania:
  tracks: [0, 1, 2, 3, 4, 5, 6, 7]
  num_leds: 24
ruins:
  tracks: [0, 1, 2, 3, 4, 5, 6, 7]
  num_leds: 24
nokia:
  tracks: [0, 1, 5, 6, 7]
  num_leds: 24
