#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

mkdir -p ${HOME}/bwbots-beer-caddy/ros1/logs
mkdir -p ${HOME}/bwbots-beer-caddy/ros1/bags

cd ${BASE_DIR}/resources

docker run -it \
    --name workstation_build_bwbots \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v /home/${USER}/bwbots-beer-caddy/ros1:/root/ros_ws:rw \
    -v=/home/${USER}/bwbots-beer-caddy/ros1/scripts:/root/scripts:rw \
    --rm \
    bwbots_workstation:latest \
    /root/install/build_bwbots.sh
