#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

cd ${BASE_DIR}/../..
docker build -f ./unity/docker/resources/Dockerfile -t bwbots_workstation:latest .

HAS_GPU=`${BASE_DIR}/has_gpu`
if [[ $HAS_GPU -eq 1 ]]; then
    cd ${BASE_DIR}/resources
    docker build -f ZED.Dockerfile -t bwbots_zed_workstation:latest .
fi

${BASE_DIR}/post_build
