#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

mkdir -p ${HOME}/bwbots-beer-caddy/ros1/logs
mkdir -p ${HOME}/bwbots-beer-caddy/ros1/bags

cd ${BASE_DIR}/resources

VALUE=`docker volume ls -f name=bwbots_workstation_build`
if ! echo ${VALUE} | grep -q "bwbots_workstation_build"; then
    echo "Creating volume"
    docker volume create bwbots_workstation_build
fi

docker run -it \
    --name workstation_build_bwbots \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=bwbots_workstation_build:/root/ros_ws:rw \
    -v=/home/${USER}/bwbots-beer-caddy:/root/bwbots-beer-caddy:rw \
    -v=/home/${USER}/bwbots-beer-caddy/ros1/scripts:/root/scripts:rw \
    --rm \
    bwbots_workstation:latest \
    /root/install/copy_bwbots.sh
