#!/bin/bash

function cleanup {
    xhost -local:root
}
trap cleanup EXIT

xhost +local:root

docker exec -t -it \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    bwbots_devcontainer \
    env TERM=xterm-256color \
    /bin/bash
