#!/bin/bash
which nvidia-smi > /dev/null
if [[ $? -eq 1 ]]; then
    HAS_GPU="0"
else
    nvidia-smi -L > /dev/null
    num_gpus=$?
    if ((num_gpus == 0)); then
        HAS_GPU="1"
    else
        HAS_GPU="0"
    fi
fi

echo $HAS_GPU
