#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
fi

cd ..

apt install -y apt-transport-https ca-certificates curl \
	gnupg-agent software-properties-common

# Repo Key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

# Repo Itself
add-apt-repository -y \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

apt-get update
apt-get install -y docker docker-ce-cli containerd.io docker-compose

usermod -aG docker $USER
systemctl enable docker

udevadm control --reload-rules && udevadm trigger

systemctl restart docker
