#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

function cleanup {
    xhost -local:root
}
trap cleanup EXIT

HOST_MACHINE=$1
JOYSTICK_DEVICE=$2

xhost +local:root
docker run -it \
    --name workstation_zed \
    --env="HOST_MACHINE=$HOST_MACHINE" \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=/home/${USER}/bwbots-beer-caddy/ros1/bwbots/bw_zed:/root/ros_ws/src/bw_zed:rw \
    -v=/home/${USER}/bwbots-beer-caddy/unity/docker/resources/scripts:/root/scripts:rw \
    -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --rm \
    bwbots_zed_workstation:latest \
    /entrypoint.sh roslaunch bw_zed zed1.launch
