#!/bin/bash
function cleanup {
    xhost -local:root
}
trap cleanup EXIT

HOST_MACHINE=$1
CONFIG=${2:-standard.rviz}

xhost +local:root
docker run -it \
    --name workstation_rviz \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --env="HOST_MACHINE=$HOST_MACHINE" \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=/home/${USER}/bwbots-beer-caddy/ros1:/root/ros_ws:rw \
    -v=/home/${USER}/bwbots-beer-caddy/ros1/scripts:/root/scripts:rw \
    -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --rm \
    bwbots_workstation:latest \
    /entrypoint.sh rviz -d /root/ros_ws/src/bwbots/bw_viz/rviz/${CONFIG}
