#!/bin/bash
function cleanup {
    xhost -local:root
}
trap cleanup EXIT

COMMAND=$1
HOST_MACHINE=$2

xhost +local:root
docker run -it \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --env="HOST_MACHINE=$HOST_MACHINE" \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=/home/${USER}/docker_ros_ws:/root/ros_ws:rw \
    -v=/home/${USER}/bwbots-beer-caddy/ros1/bags:/root/bags:rw \
    -v=/home/${USER}/bwbots-beer-caddy/ros1/logs:/root/logs:rw \
    -v=/home/${USER}/bwbots-beer-caddy/ros1/bwbots:/root/ros_ws/src/bwbots:rw \
    -v=/home/${USER}/bwbots-beer-caddy/unity/docker/resources/scripts:/root/scripts:rw \
    -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --rm \
    bwbots_workstation:latest \
    /entrypoint.sh ${COMMAND}
