log:
  name: "home-delivery-bot"
  directory: "logs"
  level: 10
#  level: 20
  suffix: "%Y-%m-%d"
  file_name: "{name}-{date:%Y-%m-%d}.log"
  format: "%(levelname)s\t%(asctime)s\t[%(name)s, %(filename)s:%(lineno)d]\t%(message)s"

tunnel:
  address: /dev/ttyTHS0

joystick:
  address: /dev/input/js0
  axis_mapping: {}
  button_mapping: {}

tcp:
  host: "127.0.0.1"
  port: 3625
