tcp:
  host: "192.168.0.196"

joystick:
  address: /dev/input/js1
  button_mapping:
    main:
      A: 0
      B: 1
      X: 2
      Y: 3
    triggers:
      L1: 4
      R1: 5
    menu:
      Select: 6
      Start: 7
      Home: 8
    sticks:
      L: 9
      R: 10
