#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

PROJECT_DIR=$(realpath "${BASE_DIR}/../../")

${BASE_DIR}/copy_project

cd ${BASE_DIR}/../resources

IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
IMAGE_PREFIX=$(${BASE_DIR}/get_built_image)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
PROJECT_NAME=$(${BASE_DIR}/../get_project_name)

if [ "${IMAGE_PREFIX}" == "workstation" ]; then
    BUILD_FLAGS='-DCATKIN_BLACKLIST_PACKAGES=bw_yolo'
else
    BUILD_FLAGS=-DCATKIN_BLACKLIST_PACKAGES=\'\'
fi

docker run -it \
    --user ${ORGANIZATION} \
    --name workstation_build_${PROJECT_NAME} \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=workstation_${PROJECT_NAME}_build:/home/${ORGANIZATION}/ros_ws:rw \
    -v=${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw \
    -v=${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw \
    --rm \
    ${IMAGE_PREFIX}_${IMAGE_VERSION} \
    /opt/${ORGANIZATION}/scripts/build_ros_ws.sh ${BUILD_FLAGS}
