#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
${BASE_DIR}/stop_all_containers
docker rm $(docker ps -aq)
docker volume rm workstation_${PROJECT_NAME}_build
${BASE_DIR}/build_ros_ws
