#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

ORGANIZATION=$(${BASE_DIR}/../get_organization)
docker exec -it \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    ${ORGANIZATION}_devcontainer \
    env TERM=xterm-256color \
    /opt/${ORGANIZATION}/entrypoint.sh /bin/bash
