#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

export IMAGE_PREFIX=$(${BASE_DIR}/get_built_image)
export PROJECT_DIR=$(realpath "${BASE_DIR}/../../")
export PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
export IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
export ORGANIZATION=$(${BASE_DIR}/../get_organization)

cd ${BASE_DIR}/../resources
docker-compose -f docker-compose.workstation_roscore.yml -f docker-compose.workstation_${PROJECT_NAME}.yml up -d
