#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")

REMOTE_MACHINE=$1
LAUNCH_FILE=${2:-standard.launch}

PROJECT_DIR=$(realpath "${BASE_DIR}/../../")
IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
IMAGE_PREFIX=$(${BASE_DIR}/get_built_image)
ORGANIZATION=$(${BASE_DIR}/../get_organization)

docker run -it \
    --name workstation_${ORGANIZATION}_rviz \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --env="REMOTE_MACHINE=$REMOTE_MACHINE" \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=workstation_${ORGANIZATION}_build:/home/${ORGANIZATION}/ros_ws:rw \
    -v=${PROJECT_DIR}:/opt/${ORGANIZATION}/${ORGANIZATION}:rw \
    -v=${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw \
    --rm \
    ${IMAGE_PREFIX}_${IMAGE_VERSION} \
    /opt/${ORGANIZATION}/entrypoint.sh roslaunch ${ORGANIZATION}_viz ${LAUNCH_FILE}
