#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

export ROS_MASTER_INTERFACE=$1

if [ -z $ROS_MASTER_INTERFACE ]; then
    echo 'Provide interface to host roscore on'
    exit 1
fi

IMAGE_PREFIX=$(${BASE_DIR}/get_built_image)
export IMAGE_VERSION=${IMAGE_PREFIX}_$(${BASE_DIR}/../get_image_tag)

cd ${BASE_DIR}/../resources
docker-compose -f docker-compose.workstation_roscore.yml up -d
