#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")


REMOTE_MACHINE=$1
JOYSTICK_DEVICE=$2

PROJECT_DIR=$(realpath "${BASE_DIR}/../../")
IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
IMAGE_PREFIX=workstation

docker run -it \
    --name workstation_${ORGANIZATION}_joystick \
    --env="REMOTE_MACHINE=$REMOTE_MACHINE" \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=workstation_${ORGANIZATION}_build:/home/${ORGANIZATION}/ros_ws:rw \
    -v=${PROJECT_DIR}:/opt/${ORGANIZATION}/${ORGANIZATION}:rw \
    -v=${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw \
    --rm \
    ${IMAGE_PREFIX}_${IMAGE_VERSION} \
    /opt/${ORGANIZATION}/entrypoint.sh roslaunch ${ORGANIZATION}_debug_joystick remote_joystick.launch device:=$JOYSTICK_DEVICE
