#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
IMAGE_PREFIX=$(${BASE_DIR}/get_built_image)
docker exec -it \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    ${IMAGE_PREFIX}_${PROJECT_NAME} \
    env TERM=xterm-256color \
    /opt/${ORGANIZATION}/entrypoint.sh logs
