#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

mkdir -p ${HOME}/docker_ros_ws/src
mkdir -p ${HOME}/docker_ros_ws/devel
touch ${HOME}/docker_ros_ws/devel/setup.bash
mkdir -p ${HOME}/bwbots-beer-caddy/ros1/logs
mkdir -p ${HOME}/bwbots-beer-caddy/ros1/bags

cd ${BASE_DIR}/resources

docker run -it \
    --name workstation_build_bwbots \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v /home/${USER}/bwbots-beer-caddy/ros1/bwbots:/root/ros_ws/src/bwbots:rw \
    -v /home/${USER}/docker_ros_ws:/root/ros_ws:rw \
    --rm \
    bwbots_workstation:latest \
    /root/install/build_bwbots.sh
