#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
fi

cd ${BASE_DIR}/../../..
docker build -f ./ros1/docker/workstation/resources/Dockerfile -t bwbots_workstation:latest .

${BASE_DIR}/post_build
