geometry_msgs/PoseStamped goal
float64 xy_tolerance
float64 yaw_tolerance
duration timeout
bool ignore_obstacles
float64 reference_linear_speed
float64 reference_angular_speed
bool allow_reverse
bool rotate_in_place_start
bool rotate_in_place_end
---
bool success
---
geometry_msgs/PoseStamped current_pose
geometry_msgs/PoseStamped goal_pose
