find_tag:
  num_samples: 10
  timeout: 5.0
  stale_tag_time: 0.25

go_to_pose:
  controller_type: strafe
  x_kP: 1.1
  x_kI: 0.0
  x_kD: 0.0
  y_kP: 1.1
  y_kI: 0.0
  y_kD: 0.0
  linear_min_vel: 0.015
  linear_zero_vel: 0.014
  linear_max_vel: 1.0
  linear_max_accel: 2.0
  theta_kP: 3.0
  theta_kI: 0.0
  theta_kD: 0.0
  ramsete_b: 2.0
  ramsete_zeta: 0.7
  theta_zero_vel: 0.00001
  theta_min_vel: 0.015
  theta_max_vel: 3.0
  theta_max_accel: 1.0
  loop_rate: 50.0
  global_frame: "odom"
  robot_frame: "base_link"
  settling_time: 0.5

go_to_waypoint:
  move_base_namespace: /move_base

shuffle_until_charging:
  is_charging_cooldown: 1.0
  speed: 0.3
  loop_rate: 10.0
  interval: 0.5
