scan_filter_chain:
- name: range_filter
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.05
    upper_threshold: 24.0
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -0.785
    upper_angle: 0.785
