//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class BwDriveStateMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/BwDriveState";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public BwDriveModuleMsg[] modules;

        public BwDriveStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.modules = new BwDriveModuleMsg[0];
        }

        public BwDriveStateMsg(Std.HeaderMsg header, BwDriveModuleMsg[] modules)
        {
            this.header = header;
            this.modules = modules;
        }

        public static BwDriveStateMsg Deserialize(MessageDeserializer deserializer) => new BwDriveStateMsg(deserializer);

        private BwDriveStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.modules, BwDriveModuleMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.modules);
            serializer.Write(this.modules);
        }

        public override string ToString()
        {
            return "BwDriveStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nmodules: " + System.String.Join(", ", modules.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
