//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class BwDriveModuleMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/BwDriveModule";
        public override string RosMessageName => k_RosMessageName;

        public string module_index;
        public double azimuth_position;
        public double wheel_position;
        public double wheel_velocity;
        public double azimuth_position_setpoint;
        public double wheel_velocity_setpoint;

        public BwDriveModuleMsg()
        {
            this.module_index = "";
            this.azimuth_position = 0.0;
            this.wheel_position = 0.0;
            this.wheel_velocity = 0.0;
            this.azimuth_position_setpoint = 0.0;
            this.wheel_velocity_setpoint = 0.0;
        }

        public BwDriveModuleMsg(string module_index, double azimuth_position, double wheel_position, double wheel_velocity, double azimuth_position_setpoint, double wheel_velocity_setpoint)
        {
            this.module_index = module_index;
            this.azimuth_position = azimuth_position;
            this.wheel_position = wheel_position;
            this.wheel_velocity = wheel_velocity;
            this.azimuth_position_setpoint = azimuth_position_setpoint;
            this.wheel_velocity_setpoint = wheel_velocity_setpoint;
        }

        public static BwDriveModuleMsg Deserialize(MessageDeserializer deserializer) => new BwDriveModuleMsg(deserializer);

        private BwDriveModuleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.module_index);
            deserializer.Read(out this.azimuth_position);
            deserializer.Read(out this.wheel_position);
            deserializer.Read(out this.wheel_velocity);
            deserializer.Read(out this.azimuth_position_setpoint);
            deserializer.Read(out this.wheel_velocity_setpoint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.module_index);
            serializer.Write(this.azimuth_position);
            serializer.Write(this.wheel_position);
            serializer.Write(this.wheel_velocity);
            serializer.Write(this.azimuth_position_setpoint);
            serializer.Write(this.wheel_velocity_setpoint);
        }

        public override string ToString()
        {
            return "BwDriveModuleMsg: " +
            "\nmodule_index: " + module_index.ToString() +
            "\nazimuth_position: " + azimuth_position.ToString() +
            "\nwheel_position: " + wheel_position.ToString() +
            "\nwheel_velocity: " + wheel_velocity.ToString() +
            "\nazimuth_position_setpoint: " + azimuth_position_setpoint.ToString() +
            "\nwheel_velocity_setpoint: " + wheel_velocity_setpoint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
