//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class BwSequenceMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/BwSequence";
        public override string RosMessageName => k_RosMessageName;

        public byte serial;
        public BwSequenceElementMsg[] sequence;

        public BwSequenceMsg()
        {
            this.serial = 0;
            this.sequence = new BwSequenceElementMsg[0];
        }

        public BwSequenceMsg(byte serial, BwSequenceElementMsg[] sequence)
        {
            this.serial = serial;
            this.sequence = sequence;
        }

        public static BwSequenceMsg Deserialize(MessageDeserializer deserializer) => new BwSequenceMsg(deserializer);

        private BwSequenceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.serial);
            deserializer.Read(out this.sequence, BwSequenceElementMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.serial);
            serializer.WriteLength(this.sequence);
            serializer.Write(this.sequence);
        }

        public override string ToString()
        {
            return "BwSequenceMsg: " +
            "\nserial: " + serial.ToString() +
            "\nsequence: " + System.String.Join(", ", sequence.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
