//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class BwSequenceStateMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/BwSequenceState";
        public override string RosMessageName => k_RosMessageName;

        public byte serial;
        public bool is_from_flash;
        public bool is_running;
        public ushort index;

        public BwSequenceStateMsg()
        {
            this.serial = 0;
            this.is_from_flash = false;
            this.is_running = false;
            this.index = 0;
        }

        public BwSequenceStateMsg(byte serial, bool is_from_flash, bool is_running, ushort index)
        {
            this.serial = serial;
            this.is_from_flash = is_from_flash;
            this.is_running = is_running;
            this.index = index;
        }

        public static BwSequenceStateMsg Deserialize(MessageDeserializer deserializer) => new BwSequenceStateMsg(deserializer);

        private BwSequenceStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.serial);
            deserializer.Read(out this.is_from_flash);
            deserializer.Read(out this.is_running);
            deserializer.Read(out this.index);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.serial);
            serializer.Write(this.is_from_flash);
            serializer.Write(this.is_running);
            serializer.Write(this.index);
        }

        public override string ToString()
        {
            return "BwSequenceStateMsg: " +
            "\nserial: " + serial.ToString() +
            "\nis_from_flash: " + is_from_flash.ToString() +
            "\nis_running: " + is_running.ToString() +
            "\nindex: " + index.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
