//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class DrinkMissionArrayMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/DrinkMissionArray";
        public override string RosMessageName => k_RosMessageName;

        public DrinkMissionMsg[] missions;

        public DrinkMissionArrayMsg()
        {
            this.missions = new DrinkMissionMsg[0];
        }

        public DrinkMissionArrayMsg(DrinkMissionMsg[] missions)
        {
            this.missions = missions;
        }

        public static DrinkMissionArrayMsg Deserialize(MessageDeserializer deserializer) => new DrinkMissionArrayMsg(deserializer);

        private DrinkMissionArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.missions, DrinkMissionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.missions);
            serializer.Write(this.missions);
        }

        public override string ToString()
        {
            return "DrinkMissionArrayMsg: " +
            "\nmissions: " + System.String.Join(", ", missions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
