//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class DrinkMissionMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/DrinkMission";
        public override string RosMessageName => k_RosMessageName;

        public string delivery_waypoint_key;
        public string drink_dispenser_tag;

        public DrinkMissionMsg()
        {
            this.delivery_waypoint_key = "";
            this.drink_dispenser_tag = "";
        }

        public DrinkMissionMsg(string delivery_waypoint_key, string drink_dispenser_tag)
        {
            this.delivery_waypoint_key = delivery_waypoint_key;
            this.drink_dispenser_tag = drink_dispenser_tag;
        }

        public static DrinkMissionMsg Deserialize(MessageDeserializer deserializer) => new DrinkMissionMsg(deserializer);

        private DrinkMissionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.delivery_waypoint_key);
            deserializer.Read(out this.drink_dispenser_tag);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.delivery_waypoint_key);
            serializer.Write(this.drink_dispenser_tag);
        }

        public override string ToString()
        {
            return "DrinkMissionMsg: " +
            "\ndelivery_waypoint_key: " + delivery_waypoint_key.ToString() +
            "\ndrink_dispenser_tag: " + drink_dispenser_tag.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
