//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class LoadCellMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/LoadCell";
        public override string RosMessageName => k_RosMessageName;

        public float mass;
        //  kilograms

        public LoadCellMsg()
        {
            this.mass = 0.0f;
        }

        public LoadCellMsg(float mass)
        {
            this.mass = mass;
        }

        public static LoadCellMsg Deserialize(MessageDeserializer deserializer) => new LoadCellMsg(deserializer);

        private LoadCellMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mass);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mass);
        }

        public override string ToString()
        {
            return "LoadCellMsg: " +
            "\nmass: " + mass.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
