geometry_msgs/PoseStamped goal
float64 linear_tolerance
float64 angle_tolerance
duration timeout
float64 reference_linear_speed
float64 reference_angular_speed
float64 linear_max_accel
float64 linear_min_vel
float64 angle_max_accel
float64 angle_min_vel
---
bool success
---
geometry_msgs/PoseStamped current_pose
geometry_msgs/PoseStamped goal_pose
