#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")
PARENT_DIR=$(dirname $BASE_DIR)
DESTINATION_NAME=$1
REMOTE_KEY=$2
RESTART_SERVICE=$3
USERNAME=${4:-bw}
SERVICE_NAME=bwbots

LOCAL_PATH=${PARENT_DIR}
DESTINATION_PATH=/home/${USERNAME}

if [ -z ${DESTINATION_NAME} ]; then
    echo "Please set a destination IP or hostname"
    exit
fi

if [ -z ${REMOTE_KEY} ]; then
    echo "Please set an SSH key file"
    exit
fi

LOCAL_PATH=$(realpath $LOCAL_PATH)
LOCAL_NAME=$(basename $LOCAL_PATH)
DEST_FULL_PATH=${DESTINATION_PATH}/${LOCAL_NAME}
CATKIN_WS_PATH=${DESTINATION_PATH}/ros_ws
PACKAGES_PATH=${LOCAL_PATH}/ros1/bwbots

${BASE_DIR}/upload ${DESTINATION_NAME} ${REMOTE_KEY} n ${USERNAME}

SSH_COMMAND="ssh -i ${REMOTE_KEY} ${USERNAME}@${DESTINATION_NAME}"

# build bwbots
${SSH_COMMAND} "sudo ${DEST_FULL_PATH}/ros1/docker/native/build_container"

${BASE_DIR}/restart ${DESTINATION_NAME} ${REMOTE_KEY} ${RESTART_SERVICE}
