#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")
PARENT_DIR=$(dirname $BASE_DIR)
DESTINATION_NAME=$1
REMOTE_KEY=$2
RESTART_SERVICE=$3
REMOTE_USER_NAME=$4

LOCAL_PATH=${PARENT_DIR}
DESTINATION_PATH=/home/${REMOTE_USER_NAME}

if [ -z ${DESTINATION_NAME} ]; then
    echo "Please set a destination IP or hostname"
    exit
fi

if [ -z ${REMOTE_KEY} ]; then
    echo "Please set an SSH key file"
    exit
fi

LOCAL_PATH=$(realpath $LOCAL_PATH)
LOCAL_NAME=$(basename $LOCAL_PATH)
DEST_FULL_PATH=${DESTINATION_PATH}/${LOCAL_NAME}
PACKAGES_PATH=${LOCAL_PATH}

${BASE_DIR}/upload ${DESTINATION_NAME} ${REMOTE_KEY} n ${REMOTE_USER_NAME}

SSH_COMMAND="ssh -i ${REMOTE_KEY} ${REMOTE_USER_NAME}@${DESTINATION_NAME}"

# build project
${SSH_COMMAND} "sudo ${DEST_FULL_PATH}/docker/jetson/build_container"

${BASE_DIR}/restart ${DESTINATION_NAME} ${REMOTE_KEY} ${RESTART_SERVICE} ${REMOTE_USER_NAME}
