version: "3"

services:
  training_bwbots:
    image: training_bwbots:latest
    container_name: training_bwbots
    restart: "no"
    network_mode: "host"
    privileged: true
    stop_signal: SIGINT
    ports: ["9090:9090", "10000:10000"]
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    # Share IPC with the host: enables us to request X to draw things, see
    # https://askubuntu.com/questions/1237400/how-to-fix-x-error-badaccess-baddrawable-badshmseg-while-running-graphical-ap
    ipc: host
    volumes:
      - ${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw
      - ${PROJECT_DIR}/logs:/opt/${ORGANIZATION}/logs:rw
      - ${PROJECT_DIR}/bags:/opt/${ORGANIZATION}/bags:rw
    command: ["/opt/${ORGANIZATION}/launch.sh"]
