version: "3"
volumes:
  bwbots-beer-caddy_build:
    name: bwbots-beer-caddy_build
    external: true

services:
  bwbots-beer-caddy:
    image: ${IMAGE_VERSION}
    container_name: bwbots-beer-caddy
    restart: "no"
    network_mode: "host"
    runtime: "nvidia"
    privileged: true
    stop_signal: SIGINT
    environment:
      - ROS_MASTER_INTERFACE=wlan0
    group_add:
      - dialout
    volumes:
      - ${PROJECT_NAME}_build:/home/${ORGANIZATION}/ros_ws:rw
      - ${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw
      - ${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw
      - /home/${USER}/.robot:/opt/${ORGANIZATION}/robot:rw
      - /media/storage:/media/storage:rw
      - /run/systemd:/run/systemd:rw
      - /dev:/dev:rw
      # Allow container to control NetworkManager
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    command: ["/opt/${ORGANIZATION}/launch.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
