#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

${BASE_DIR}/copy_bwbots

cd ${BASE_DIR}/../resources

docker-compose -f docker-compose.bwbots.yml stop

docker run \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=bwbots_build:/root/ros_ws:rw \
    -v=/home/${USER}/bwbots-beer-caddy:/root/bwbots-beer-caddy:rw \
    -v=/home/${USER}/bwbots-beer-caddy/ros1/scripts:/root/scripts:rw \
    --rm \
    --gpus all \
    bwbots:latest \
    /root/scripts/build_bwbots.sh
