#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
fi

cd ${BASE_DIR}/../resources
docker-compose -f docker-compose.roscore.yml -f docker-compose.bwbots.yml stop
docker build -f ./Dockerfile -t bwbots:latest .
