#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

VALUE=`docker volume ls -f name=bwbots_build`
if ! echo ${VALUE} | grep -q "bwbots_build"; then
    echo "Creating volume"
    docker volume create bwbots_build
fi

docker run \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=bwbots_build:/root/ros_ws:rw \
    -v=/home/${USER}/bwbots-beer-caddy:/root/bwbots-beer-caddy:rw \
    -v=/home/${USER}/bwbots-beer-caddy/ros1/scripts:/root/scripts:rw \
    --rm \
    --gpus all \
    bwbots:latest \
    /root/scripts/copy_bwbots.sh
