#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
fi

cd ..

apt install -y apt-transport-https ca-certificates curl \
	gnupg-agent software-properties-common

# Repo Key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

# Repo Itself
add-apt-repository -y \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

apt-get update
apt-get install -y docker docker-ce-cli containerd.io

usermod -aG docker $USER
systemctl enable docker

udevadm control --reload-rules && udevadm trigger

#Install Docker Compose
export DOCKER_COMPOSE_INSTALL_PATH=/usr/local/lib/docker/cli-plugins
export DOCKER_COMPOSE_URL=https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-linux-armv7

mkdir -p ${DOCKER_COMPOSE_INSTALL_PATH}
curl -SL ${DOCKER_COMPOSE_URL} -o ${DOCKER_COMPOSE_INSTALL_PATH}/docker-compose
chmod +x ${DOCKER_COMPOSE_INSTALL_PATH}/docker-compose
curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sh

apt-get install -y nvidia-container-runtime
apt-get install -y docker.io containerd

cp ${BASE_DIR}/daemon.json /etc/docker/daemon.json

systemctl restart docker
