global_frame: odom
robot_base_frame: base_link
update_frequency: 3.0
publish_frequency: 1.0
width: 2.0
height: 2.0
# origin_x: -1.5
# origin_y: -1.5
resolution: 0.04
# static_map: false  # unnecessary with plugins
rolling_window: true

footprint_padding: 0.0

inflation:
    enabled: true
    cost_scaling_factor: 3.0
    inflation_radius: 1.5

obstacle_layer:
    enabled: true
    origin_z: 0.0
    z_resolution: 0.2
    z_voxels: 10
    publish_voxel_map: false

    observation_sources: point_cloud_sensor laser_sensor
    point_cloud_sensor:
        sensor_frame: camera_link
        data_type: PointCloud2
        topic: /zed/point_cloud/cloud_registered
        marking: true
        clearing: true

        obstacle_range: 1.0
        raytrace_range: 1.0
        max_obstacle_height: 0.4
        min_obstacle_height: 0.05
        inflation_radius: 0.01
        track_unknown_space: true
        combination_method: 1
        
    laser_sensor:
        sensor_frame: laser
        data_type: LaserScan
        topic: /laser/scan_filtered
        marking: true
        clearing: true
        inflation_radius: 0.005
        raytrace_range: 1.0
        obstacle_range: 1.0


plugins:
    - {name: static,                    type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer,            type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_layer,            type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
