move_base:
  package: "bw_move_base"
  path: "bw_move_base.launch"
  on_start: true
  topics:
    /move_base: None

behaviors:
  package: "bw_behaviors"
  path: "bw_behaviors.launch"
  on_start: true

tags:
  package: "bw_tags"
  path: "left_tags.launch"
  on_start: true

zed:
  package: "bw_zed"
  path: "zed2.launch"
  on_start: true
