//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class FindTagFeedback : Message
    {
        public const string k_RosMessageName = "bw_interfaces/FindTag";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseStampedMsg sample;
        public int num_samples;

        public FindTagFeedback()
        {
            this.sample = new Geometry.PoseStampedMsg();
            this.num_samples = 0;
        }

        public FindTagFeedback(Geometry.PoseStampedMsg sample, int num_samples)
        {
            this.sample = sample;
            this.num_samples = num_samples;
        }

        public static FindTagFeedback Deserialize(MessageDeserializer deserializer) => new FindTagFeedback(deserializer);

        private FindTagFeedback(MessageDeserializer deserializer)
        {
            this.sample = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.num_samples);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sample);
            serializer.Write(this.num_samples);
        }

        public override string ToString()
        {
            return "FindTagFeedback: " +
            "\nsample: " + sample.ToString() +
            "\nnum_samples: " + num_samples.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
