//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class FollowWaypointsGoal : Message
    {
        public const string k_RosMessageName = "bw_interfaces/FollowWaypoints";
        public override string RosMessageName => k_RosMessageName;

        public WaypointArrayMsg waypoints;

        public FollowWaypointsGoal()
        {
            this.waypoints = new WaypointArrayMsg();
        }

        public FollowWaypointsGoal(WaypointArrayMsg waypoints)
        {
            this.waypoints = waypoints;
        }

        public static FollowWaypointsGoal Deserialize(MessageDeserializer deserializer) => new FollowWaypointsGoal(deserializer);

        private FollowWaypointsGoal(MessageDeserializer deserializer)
        {
            this.waypoints = WaypointArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.waypoints);
        }

        public override string ToString()
        {
            return "FollowWaypointsGoal: " +
            "\nwaypoints: " + waypoints.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
