//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class FollowWaypointsFeedback : Message
    {
        public const string k_RosMessageName = "bw_interfaces/FollowWaypoints";
        public override string RosMessageName => k_RosMessageName;

        public WaypointMsg current_goal;
        public Geometry.PoseStampedMsg current_pose;

        public FollowWaypointsFeedback()
        {
            this.current_goal = new WaypointMsg();
            this.current_pose = new Geometry.PoseStampedMsg();
        }

        public FollowWaypointsFeedback(WaypointMsg current_goal, Geometry.PoseStampedMsg current_pose)
        {
            this.current_goal = current_goal;
            this.current_pose = current_pose;
        }

        public static FollowWaypointsFeedback Deserialize(MessageDeserializer deserializer) => new FollowWaypointsFeedback(deserializer);

        private FollowWaypointsFeedback(MessageDeserializer deserializer)
        {
            this.current_goal = WaypointMsg.Deserialize(deserializer);
            this.current_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_goal);
            serializer.Write(this.current_pose);
        }

        public override string ToString()
        {
            return "FollowWaypointsFeedback: " +
            "\ncurrent_goal: " + current_goal.ToString() +
            "\ncurrent_pose: " + current_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
