//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class GoToPoseFeedback : Message
    {
        public const string k_RosMessageName = "bw_interfaces/GoToPose";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseStampedMsg current_pose;
        public Geometry.PoseStampedMsg goal_pose;

        public GoToPoseFeedback()
        {
            this.current_pose = new Geometry.PoseStampedMsg();
            this.goal_pose = new Geometry.PoseStampedMsg();
        }

        public GoToPoseFeedback(Geometry.PoseStampedMsg current_pose, Geometry.PoseStampedMsg goal_pose)
        {
            this.current_pose = current_pose;
            this.goal_pose = goal_pose;
        }

        public static GoToPoseFeedback Deserialize(MessageDeserializer deserializer) => new GoToPoseFeedback(deserializer);

        private GoToPoseFeedback(MessageDeserializer deserializer)
        {
            this.current_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.goal_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_pose);
            serializer.Write(this.goal_pose);
        }

        public override string ToString()
        {
            return "GoToPoseFeedback: " +
            "\ncurrent_pose: " + current_pose.ToString() +
            "\ngoal_pose: " + goal_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
