//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class HasDrinkGoal : Message
    {
        public const string k_RosMessageName = "bw_interfaces/HasDrink";
        public override string RosMessageName => k_RosMessageName;

        public DurationMsg timeout;
        public float mass_threshold;

        public HasDrinkGoal()
        {
            this.timeout = new DurationMsg();
            this.mass_threshold = 0.0f;
        }

        public HasDrinkGoal(DurationMsg timeout, float mass_threshold)
        {
            this.timeout = timeout;
            this.mass_threshold = mass_threshold;
        }

        public static HasDrinkGoal Deserialize(MessageDeserializer deserializer) => new HasDrinkGoal(deserializer);

        private HasDrinkGoal(MessageDeserializer deserializer)
        {
            this.timeout = DurationMsg.Deserialize(deserializer);
            deserializer.Read(out this.mass_threshold);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timeout);
            serializer.Write(this.mass_threshold);
        }

        public override string ToString()
        {
            return "HasDrinkGoal: " +
            "\ntimeout: " + timeout.ToString() +
            "\nmass_threshold: " + mass_threshold.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
