//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class HasDrinkResult : Message
    {
        public const string k_RosMessageName = "bw_interfaces/HasDrink";
        public override string RosMessageName => k_RosMessageName;

        public bool has_drink;
        public bool success;

        public HasDrinkResult()
        {
            this.has_drink = false;
            this.success = false;
        }

        public HasDrinkResult(bool has_drink, bool success)
        {
            this.has_drink = has_drink;
            this.success = success;
        }

        public static HasDrinkResult Deserialize(MessageDeserializer deserializer) => new HasDrinkResult(deserializer);

        private HasDrinkResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.has_drink);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.has_drink);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "HasDrinkResult: " +
            "\nhas_drink: " + has_drink.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
