//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class RunBehaviorFeedback : Message
    {
        public const string k_RosMessageName = "bw_interfaces/RunBehavior";
        public override string RosMessageName => k_RosMessageName;

        public string status;
        public string node_name;

        public RunBehaviorFeedback()
        {
            this.status = "";
            this.node_name = "";
        }

        public RunBehaviorFeedback(string status, string node_name)
        {
            this.status = status;
            this.node_name = node_name;
        }

        public static RunBehaviorFeedback Deserialize(MessageDeserializer deserializer) => new RunBehaviorFeedback(deserializer);

        private RunBehaviorFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.node_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.node_name);
        }

        public override string ToString()
        {
            return "RunBehaviorFeedback: " +
            "\nstatus: " + status.ToString() +
            "\nnode_name: " + node_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
