//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class RunBehaviorGoal : Message
    {
        public const string k_RosMessageName = "bw_interfaces/RunBehavior";
        public override string RosMessageName => k_RosMessageName;

        public string behavior;

        public RunBehaviorGoal()
        {
            this.behavior = "";
        }

        public RunBehaviorGoal(string behavior)
        {
            this.behavior = behavior;
        }

        public static RunBehaviorGoal Deserialize(MessageDeserializer deserializer) => new RunBehaviorGoal(deserializer);

        private RunBehaviorGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.behavior);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.behavior);
        }

        public override string ToString()
        {
            return "RunBehaviorGoal: " +
            "\nbehavior: " + behavior.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
