//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class RunSequenceFeedback : Message
    {
        public const string k_RosMessageName = "bw_interfaces/RunSequence";
        public override string RosMessageName => k_RosMessageName;

        public ushort index;

        public RunSequenceFeedback()
        {
            this.index = 0;
        }

        public RunSequenceFeedback(ushort index)
        {
            this.index = index;
        }

        public static RunSequenceFeedback Deserialize(MessageDeserializer deserializer) => new RunSequenceFeedback(deserializer);

        private RunSequenceFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.index);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.index);
        }

        public override string ToString()
        {
            return "RunSequenceFeedback: " +
            "\nindex: " + index.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
