//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class RunSequenceResult : Message
    {
        public const string k_RosMessageName = "bw_interfaces/RunSequence";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public RunSequenceResult()
        {
            this.success = false;
        }

        public RunSequenceResult(bool success)
        {
            this.success = success;
        }

        public static RunSequenceResult Deserialize(MessageDeserializer deserializer) => new RunSequenceResult(deserializer);

        private RunSequenceResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "RunSequenceResult: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
