//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class RunSequenceGoal : Message
    {
        public const string k_RosMessageName = "bw_interfaces/RunSequence";
        public override string RosMessageName => k_RosMessageName;

        public byte serial;
        public bool loop;
        public bool from_flash;

        public RunSequenceGoal()
        {
            this.serial = 0;
            this.loop = false;
            this.from_flash = false;
        }

        public RunSequenceGoal(byte serial, bool loop, bool from_flash)
        {
            this.serial = serial;
            this.loop = loop;
            this.from_flash = from_flash;
        }

        public static RunSequenceGoal Deserialize(MessageDeserializer deserializer) => new RunSequenceGoal(deserializer);

        private RunSequenceGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.serial);
            deserializer.Read(out this.loop);
            deserializer.Read(out this.from_flash);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.serial);
            serializer.Write(this.loop);
            serializer.Write(this.from_flash);
        }

        public override string ToString()
        {
            return "RunSequenceGoal: " +
            "\nserial: " + serial.ToString() +
            "\nloop: " + loop.ToString() +
            "\nfrom_flash: " + from_flash.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
