//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class ShuffleUntilChargingFeedback : Message
    {
        public const string k_RosMessageName = "bw_interfaces/ShuffleUntilCharging";
        public override string RosMessageName => k_RosMessageName;

        public int attempts;

        public ShuffleUntilChargingFeedback()
        {
            this.attempts = 0;
        }

        public ShuffleUntilChargingFeedback(int attempts)
        {
            this.attempts = attempts;
        }

        public static ShuffleUntilChargingFeedback Deserialize(MessageDeserializer deserializer) => new ShuffleUntilChargingFeedback(deserializer);

        private ShuffleUntilChargingFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.attempts);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.attempts);
        }

        public override string ToString()
        {
            return "ShuffleUntilChargingFeedback: " +
            "\nattempts: " + attempts.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
