//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class ShuffleUntilChargingGoal : Message
    {
        public const string k_RosMessageName = "bw_interfaces/ShuffleUntilCharging";
        public override string RosMessageName => k_RosMessageName;

        public DurationMsg timeout;

        public ShuffleUntilChargingGoal()
        {
            this.timeout = new DurationMsg();
        }

        public ShuffleUntilChargingGoal(DurationMsg timeout)
        {
            this.timeout = timeout;
        }

        public static ShuffleUntilChargingGoal Deserialize(MessageDeserializer deserializer) => new ShuffleUntilChargingGoal(deserializer);

        private ShuffleUntilChargingGoal(MessageDeserializer deserializer)
        {
            this.timeout = DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timeout);
        }

        public override string ToString()
        {
            return "ShuffleUntilChargingGoal: " +
            "\ntimeout: " + timeout.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
